### ISSUE TITLE
Allow config groups to accept multiple string values as inputs for `directory` 

### ISSUE THREAD

**Issue by ThomasHepworth** [ThomasHepworth/folder_cleaner#1]
At present [PathConfig](https://github.com/ThomasHepworth/folder_cleaner/blob/master/src/configs/config.rs#L95) expects a single string as a directory input.

In practice this means that the config toml file requires multiple groups be created, even when you want the same settings across these groups:
```toml
[[core]]
directory = "/Users/thomashepworth/randomer"

[[core]]
directory = "/Users/thomashepworth/random"
```

It would make more sense to allow multiple directories to be entered and fed into the system:
```toml
[[core]]
directory = [
    "/Users/thomashepworth/randomer",
    "/Users/thomashepworth/random"
]
```

and to support multiple groups where you want the settings to differ:
```toml
[[core]]
directory = "/Users/thomashepworth/randomer"
extensions_to_keep = ["png"]

[[core]]
directory = "/Users/thomashepworth/random"
extensions_to_del = ["xlsx"]
```
